FROM node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# ===============================
# BASE CONFIG
# ===============================
ARG VITE_API_BASE_URL

# ===============================
# ERP / ZRA APIs
# ===============================
ARG VITE_ZRA_CLIENT_API
ARG VITE_INVOICE_API_URL
ARG VITE_ITEM_API_URL
ARG VITE_PROFORMA_API_URL
ARG VITE_QUOTATION_API_URL
ARG VITE_DEBIT_NOTE_API_URL
ARG VITE_CREDIT_NOTE_API_URL
ARG VITE_CUSTOMER_API_URL
ARG VITE_CUSTOMER_STATEMENT_API_URL
ARG VITE_SUPPLIER_API_URL
ARG VITE_PO_API_URL

# ===============================
# COMPANY
# ===============================
ARG VITE_COMPANY_API_URL

# ===============================
# HRMS
# ===============================
ARG VITE_HRMS_API_URL
ARG VITE_NAPSA_MEMBER_API_URL

# ===============================
# LOOKUP / CODES
# ===============================
ARG VITE_ZRA_CODES_API_URL
ARG VITE_CLASS_LIST_API_URL
ARG VITE_COUNTRY_LIST_API_URL
ARG VITE_PACKAGING_UNIT_CODES_API_URL
ARG VITE_UNIT_OF_MEASURE_API_URL

# ===============================
# AUTH & OTHER
# ===============================
ARG VITE_API_AUTH_TOKEN
ARG VITE_COMPANY_ID

# ===============================
# SET ENVIRONMENT VARIABLES
# ===============================
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_ZRA_CLIENT_API=$VITE_ZRA_CLIENT_API
ENV VITE_INVOICE_API_URL=$VITE_INVOICE_API_URL
ENV VITE_ITEM_API_URL=$VITE_ITEM_API_URL
ENV VITE_PROFORMA_API_URL=$VITE_PROFORMA_API_URL
ENV VITE_QUOTATION_API_URL=$VITE_QUOTATION_API_URL
ENV VITE_DEBIT_NOTE_API_URL=$VITE_DEBIT_NOTE_API_URL
ENV VITE_CREDIT_NOTE_API_URL=$VITE_CREDIT_NOTE_API_URL
ENV VITE_CUSTOMER_API_URL=$VITE_CUSTOMER_API_URL
ENV VITE_CUSTOMER_STATEMENT_API_URL=$VITE_CUSTOMER_STATEMENT_API_URL
ENV VITE_SUPPLIER_API_URL=$VITE_SUPPLIER_API_URL
ENV VITE_PO_API_URL=$VITE_PO_API_URL
ENV VITE_COMPANY_API_URL=$VITE_COMPANY_API_URL
ENV VITE_HRMS_API_URL=$VITE_HRMS_API_URL
ENV VITE_NAPSA_MEMBER_API_URL=$VITE_NAPSA_MEMBER_API_URL
ENV VITE_ZRA_CODES_API_URL=$VITE_ZRA_CODES_API_URL
ENV VITE_CLASS_LIST_API_URL=$VITE_CLASS_LIST_API_URL
ENV VITE_COUNTRY_LIST_API_URL=$VITE_COUNTRY_LIST_API_URL
ENV VITE_PACKAGING_UNIT_CODES_API_URL=$VITE_PACKAGING_UNIT_CODES_API_URL
ENV VITE_UNIT_OF_MEASURE_API_URL=$VITE_UNIT_OF_MEASURE_API_URL
ENV VITE_API_AUTH_TOKEN=$VITE_API_AUTH_TOKEN
ENV VITE_COMPANY_ID=$VITE_COMPANY_ID

RUN npm run build

FROM node:lts-alpine AS runner

WORKDIR /app

RUN npm install -g serve

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder --chown=appuser:appgroup /app/dist ./dist

USER appuser

EXPOSE 3003
CMD ["serve", "-s", "dist", "-l", "3003"]